### ISSUE TITLE
metrics, please!

### ISSUE THREAD

**Issue by linuxcaffe** [coddingtonbear/inthe.am#111]
In my current task list I have 99 tasks pending, 140 completed, but only 8 tasks are visible on my inthe.am screen. Some clues about # of pending tasks would be great, as would the [# filtered/ of # pending] .

I don't see an obvious place to put 'em.. maybe top/center, with a grayed font-color:

Inthe.AM    Tasks    New                    (99 pending)                                  Log    Configuration    Log Out
or 
Inthe.AM    Tasks    New                    (21 of  99 pending)                 Log    Configuration    Log Out

or maybe even in a tool-tip on the Tasks button.. something!
thanks

**Comment by coddingtonbear** [comment]
At the moment this isn't likely to ever make it onto the roadmap; if you'd like to add such a feature, though, I'd be glad to review/merge your work.  Let me know if you need any pointers on how to get a pull request put together, though!

Cheers,
Adam
