### ISSUE TITLE
Prepare upgrade plan for upgrading to Taskwarrior 2.4.x and Taskd 1.1

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/inthe.am#115]
This will require:

* Verifying that new clients can sync with the old taskd.
* Verifying that upgrading to the latest version of taskwarrior will not cause a problem for our wrapper around taskw.
* Preparing a downgrade script; if this process does turn out to be a problem, downgrade all users' local task clones to the commit immediately preceding the upgrade, and initiating a sync with the taskd server.
* Probably a downtime notice?
* Lots and lots of validation of the latest version of taskw.

**Comment by sanjayankur31** [comment]
Hi,

Is intheam to work with task 2.4? Fedora 21 just got task 2.4 and I can't seem to sync with intheam anymore. This is what I get: http://paste.fedoraproject.org/190563/05493142/

Cheers,
