### ISSUE TITLE
emailing tasks does not work if you use an alias.

### ISSUE THREAD

**Issue by ddeimeke** [coddingtonbear/inthe.am#134]
I configured a forwarder from taskwarrior@example.com to <id>@inthe.am.

The forwarder is working pretty fine, but inthe.am does not take the task coming via my own domain.

Maybe the problem is that inthe.am checks for the "to:" in an email and not for "envelope-to:" or "delivered-to:".

Maybe adding a configuration switch for changing this behavior would be great.

**Comment by coddingtonbear** [comment]
Fixed via 3d7a83818c5725173be1f7d18706be27fa72d523.
