### ISSUE TITLE
Consider porting code over to use tasklib

### ISSUE THREAD

**Issue by tbabej** [coddingtonbear/inthe.am#135]
Inthe.am can use tasklib ( https://github.com/robgolding63/tasklib ) to simplify the code, since it provides pythonic access to TaskWarrior.

**Comment by coddingtonbear** [comment]
Hey there, @tbabej, as nice as tasklib looks, I'm afraid that ship sailed about a year ago.  Although on the surface, it might seem that swapping out the underlying Taskwarrior abstractions might be relatively easy, we utilize fairly advanced features of `taskw <https://github.com/ralphbean/taskw>` including UDA handling, configuration abstractions and overrides, synchronization, etc., and adding those features to tasklib would take time I'm afraid I don't have.

Thanks for the suggestion, though, @tbabej!

**Comment by tbabej** [comment]
Oh, tasklib works fine with the features you mention, it's the documentation which is lacking. But if you're already using another library, it does not make much sense to port (I was unaware of taskw when I started to extend tasklib).

**Comment by tbabej** [comment]
Taskw looks fine! (tasklib may have nicer api, but taskw on the other hand is probably more stable and tested). I created this issue since I thought you are maintaining your own layer for interacting with TaskWarrior and tasklib could take that off your hands, as it is compatible with TW 2.1+.
