### ISSUE TITLE
Consider altering display of task list such that more tasks are visible simultaneously

### ISSUE THREAD

**Issue by linuxcaffe** [coddingtonbear/inthe.am#136]
Currently, in my laptop browser, my inthe.am task list can only display about six tasks at a time. This is partly due to the new countdown display, using another line, and my smallish crappy laptop screen.

I think it would be advantageous (for me, and others in the same condition) to have the option of a "compact mode", that reduced the task listings to a single line, consisting of;

[ smaller circle-or-clock icon ] [ description, truncated ] [ tag icon ] [ annotation icon ]

and with slightly reduced padding, I'm guessing that that I could see double, maybe triple the tasks, on the same screen. 

thanks!

**Comment by coddingtonbear** [comment]
I'm really very disinclined to adding new options to Inthe.AM -- every option that is added increases maintenance complexity and makes adding future features slightly more complicated.  I am, though, willing to consider changing the CSS such that it styles the task list differently on smaller screens; what is your laptop's screen resolution?

**Comment by linuxcaffe** [comment]
Automatic css-switch would be a good alternative. 
I'm running a thinkpad T42 at 1024x786, and in a normal browser window I can see six (and a bit) tasks.

**Comment by linuxcaffe** [comment]
and on my android phone, I see four tasks..

**Comment by coddingtonbear** [comment]
I'm almost certainly never going to find the time to work on this.  @linuxcaffe -- feel free to post a PR for this, but failing that, I'm afraid this issue isn't likely to get any attention.

Cheers,
Adam
