### ISSUE TITLE
task sync: "The certificate is NOT trusted. The certificate chain uses expired certificate."

### ISSUE THREAD

**Issue by javaJake** [coddingtonbear/inthe.am#137]
<pre>
 $ task sync
c: INFO The certificate is NOT trusted. The certificate chain uses expired certificate. 
Syncing with taskwarrior.inthe.am:53589

Handshake failed.  Error in the certificate.
Sync failed.  Could not connect to the Taskserver.
</pre>

**Comment by coddingtonbear** [comment]
Working on this via #138
