### ISSUE TITLE
Handshake failed.  The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by sanjayankur31** [coddingtonbear/inthe.am#138]
Got an expired certificate error and when I downloaded the certificates again from intheam, I now get this:

```
$ task synchronize
c: INFO The certificate is trusted. 
Syncing with taskwarrior.inthe.am:53589

Handshake failed.  The TLS connection was non-properly terminated.
Sync failed.  Could not connect to the Taskserver.
```

Not quite sure how to debug it at the moment.

**Comment by sanjayankur31** [comment]
Mirakel doesn't sync either. I keep getting the "Cannot create socket" error.

**Comment by coddingtonbear** [comment]
Yep! Looking into it right now during my lunch break.  Thanks to @javaJake, it became clear that the certificate had expired.  I'm right now coding up a quick solution for re-generating everybody's certificates, and expect to have it sorted out in the next 20m or so (I hope!).

**Comment by coddingtonbear** [comment]
OK, @sanjayankur31, I haven't yet had a chance to re-generate everybody's certs, but I'll be getting to that later this evening -- for now, you can do this:

1) Log-in to your account on Inthe.AM
2) Click the 'Synchronization Settings' tab.
3) Click the 'Re-generate taskserver certificate' button.
4) Download your new certificate by clicking on the link (toward the top of that section) labeled 'private.certificate.pem'.

Let me know if you bump into any problems with those steps.  I'm re-opening this ticket until I have a chance to re-generate everybody's certificates, and will close this issue once that's complete.

**Comment by coddingtonbear** [comment]
Certificates re-generated!  I'm going to add an announcement later this afternoon to notify people logging-in that they'll need to fetch new certs; after that, this looks like it should be just fine.

**Comment by coddingtonbear** [comment]
Announcement posted; I'm calling this good-to-go now.  Cheers!

**Comment by sanjayankur31** [comment]
Tested, all OK. Thanks :)
