### ISSUE TITLE
Sync fails

### ISSUE THREAD

**Issue by orschiro** [coddingtonbear/inthe.am#139]
Hi @coddingtonbear,

Sync recently fails for me with the following message:

```
~ ❯ t sync
c: INFO The certificate is NOT trusted. The certificate issuer is unknown. 
Syncing with taskwarrior.inthe.am:53589

Handshake failed.  Error in the certificate.
Sync failed.  Could not connect to the Taskserver.
```

Excerpt of my `~/.taskrc`:

```
taskd.certificate=/home/orschiro/.task/private.certificate.pem
taskd.key=/home/orschiro/.task/private.key.pem
taskd.ca=/home/orschiro/.task/ca.cert.pem
taskd.server=taskwarrior.inthe.am:53589
taskd.credentials=inthe_am/orschiro/b92ee384-23a9-45cd-91ad-633a46f00c62
taskd.trust=ignore hostname
```

**Comment by coddingtonbear** [comment]
That looks like it's just issue #138; if you log-in to Inthe.AM's web interface, it'll let you know that you should probably download a new set of certs.

Cheers!

**Comment by orschiro** [comment]
Yes, it dit work to regenerate the certificates and download them.

Many thanks for your dedicated support!

Robert

On 15.01.2015 10:28, Adam Coddington wrote:
>
> That looks like it's just issue #138 
> <https://github.com/coddingtonbear/inthe.am/issues/138>; if you log-in 
> to Inthe.AM's web interface, it'll let you know that you should 
> probably download a new set of certs.
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/coddingtonbear/inthe.am/issues/139#issuecomment-70059876>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro
