### ISSUE TITLE
Receiving FORBIDDEN when creating a new task

### ISSUE THREAD

**Issue by philipsd6** [coddingtonbear/inthe.am#144]
After logging in with my Google account, I click on the "Create a new task" button, and save it, but receive "An error was encountered while saving your task: "FORBIDDEN"

If I click the save button again, I don't receive the error message again, but the data is not actually saved — when I look at the task list, it's blank.

FYI, I use two-step authentication on Google.

**Comment by coddingtonbear** [comment]
Hey there @philipsd6, glancing at your account, it looks like the reason you're getting that message is that you haven't yet accepted the terms of service.

When you first logged-in, it should've presented you with a long wall of text with an 'Accept' button at the bottom.  Once you've clicked that button (after reading the terms first, of course), you should be good-to-go.  If for some reason it doesn't direct you to the form immediately when you log-in, go to https://inthe.am/terms-of-service directly and let me know that it didn't redirect you automatically.

Cheers, and good luck!
