### ISSUE TITLE
Link to official Twilio pricing; allow one to disable confirmation replies.

### ISSUE THREAD

**Issue by MikeLeonard** [coddingtonbear/inthe.am#174]
Hi

Thanks for the last fix on the sms.

I'm a bit suprised at the cost of the the sms approach.  The cost of the number and the outgoing text is as you mentioned in the instructions...

"Add funds to your Twilio account. At the time of writing, Twilio charges around $0.01 for each incoming or outgoing SMS message (incoming messages are slightly cheaper), and each phone number costs $1.00/month."

... however Twilio seems to be charging me $0.04 USD for the 'Added' message that I receive back from inThe.AM, which I think over time might add up and eat through my Twilio credit.

Is that normal?  Perhaps the Twilio prices have changed?  Or perhaps did I set up the wrong type of number on Twilio? (I chose a UK mobile number that can only sms and not voice - but perhaps a landline or mobile in another country would be cheaper?)

Some thoughts...
Perhaps you can consider:
- either updating the pricing details if Twilio's pricing has indeed changed
- or perhaps add to the instructions to explain that type of number to choose (landline vs mobile etc.) if there is a cheaper approach I didn't think about
- or perhaps adding a feature to allow the user to choose whether they receive an 'Added' message (if it's not a requirement of how the system works of course).  Personally at $0.04 per 'Added' message I think this might add up over time so I would opt out of this and just know that I can look back through my sent texts if something seems missing.  (Of course a cheaper price would be the best solution though if there's a way to get that :))

Thanks again

Mike

**Comment by coddingtonbear** [comment]
I think that this is actually just a classic case of "Americans not considering the fact that people live outside the US".

In your case, your pricing numbers are available here -- https://www.twilio.com/sms/pricing/gb, and they do indeed charge about 0.04 USD per ourgoing message (which is about five times more expensive than the US!).

I hadn't really considered that outgoing messages might be so expensive, so I'm definitely in agreement on making the automatic reply a configurable feature.  Given that I've a long, long 8-hour train ride today, I'll see if I can't sort that out at some point today.

Cheers!

**Comment by coddingtonbear** [comment]
OK -- just got those changes deployed-up!  You'll now be able to find a dropdown in the 'SMS Access' section of the configuration page that will allow you to configure under what circumstances a reply should be sent to an incoming text message: 
https://www.dropbox.com/s/pbje89e8l09gnpr/Screenshot%202015-02-19%2018.01.56.png?dl=0

I hope this helps!

Cheers

**Comment by MikeLeonard** [comment]
'Reply only when an error has occurred' is a great idea :)

Thanks again for adding this so quickly, myself and other non-US Inthe.AM users thank you!

**Comment by coddingtonbear** [comment]
No problem; I'm happy to help out!

**Comment by coddingtonbear** [comment]
Incidentally, @MikeLeonard, and I'm not sure how I didn't notice this before deploying the above change, but I *just* found a bug that probably prevented you from being able to submit SMS messages.  I really, really, need to add more tests in this area of the codebase, and promise that that's on the top of my list for this week (see #178).
