### ISSUE TITLE
Dev environment error: cannot find module broccoli-ember-hbs-template-compiler

### ISSUE THREAD

**Issue by growdigital** [coddingtonbear/inthe.am#177]
I'm a front end dev/designer, looking at setting up a dev environment so I can possibly improve UI of inthe.am

I've also installed dev environment as per instructions but after running `vagrant ssh` I get an error, on the command line and in the browser. Basically:

`Error: Cannot find module '/var/www/twweb/node_modules/broccoli-ember-hbs-template-compiler'`

Full error in this gist:
https://gist.github.com/growdigital/92cc7d9dacb83b2ac2b4

I've had a look for common errors/FAQs/numpty things that can go wrong, but can't find anything!

thanks, Jake

**Comment by coddingtonbear** [comment]
Awesome -- I'm glad you're considering helping out!

Well -- looking at that, it looks like maybe it didn't successfully install the NPM packages during the initialization process.  You *might* be able to get around it by asking npm to try installing packages once again (if you get an interesting error -- please let me know); from the guest environment:

```
cd /var/www/twweb
npm install
```

That being said, If it didn't successfully install the node packages above, it *probably* didn't finish the provisioning process -- it might make more sense to instead run the following command from your clone of inthe.am in the *host* environment:

```
vagrant provision
```

Let me know if either of these help, and keep in mind that I'm always hanging out in the `##inthe.am` channel on Freenode if you bump into questions that might be better hashed-out with a real conversation.

Cheers!

**Comment by growdigital** [comment]
Thanks for helpful suggestions, sorry for delay in replying as have been offline for a couple of weeks. Will  try to get it working soon :)
