### ISSUE TITLE
cannot login with my google account

### ISSUE THREAD

**Issue by sleep-walker** [coddingtonbear/inthe.am#182]
I'm not able to login with my Google account to inthe.am.

I'm not sure how this should work, but when I failed to login, I removed all my cookies and disabled authentication on Google's side and reauthorized again, but with no change.

From Firefox POV it looks like:
1] after pressing button https://inthe.am/login/google-oauth2/ I got 302 and redirection to https://accounts.google.com/o/oauth2....
2] then I get redirection to https://inthe.am/complete/google-oauth2
3] then I get redirection to https://inthe.am/complete/google-oauth2/?state=<something>
4] then I get https://inthe.am/accounts/login
5] then I get 401 on https://inthe.am/api/v1/task/
6] then I get https://inthe.am/api/v1/user/status response in JSON containing 'logged_in: false'
7] then I get https://inthe.am/api/v1/user/announcements/ with empty JSON response

I hope that this description is not that confusing for you..

**Comment by coddingtonbear** [comment]
Hrm; I'm not able to reproduce this; are you absolutely sure you're clicking the correct buttons when you're redirected to the google login page?  I'll be glad to look up your account information in Inthe.AM if you were to let me know what your e-mail address is.

Also, note that I'm usually hanging out on IRC in the ``##inthe.am`` channel on Freenode if you have any questions.

Cheers!

**Comment by coddingtonbear** [comment]
This turned out to be a situation in which @sleep-walker's account was marked as inactive. Fixed!
