### ISSUE TITLE
inthe.am 

### ISSUE THREAD

**Issue by vhumphrey** [coddingtonbear/inthe.am#186]
Is the inthe.am site down?

**Comment by coddingtonbear** [comment]
No -- it seems to be loading just fine for me.

**Comment by coddingtonbear** [comment]
Oh, but it does look like the taskserver was down for a bit; there was a power outage at the location where the server runs a few days ago, and it doesn't look like the monitoring came back online when it restarted.  Thanks for the heads-up.

**Comment by vhumphrey** [comment]
Anytime.
