### ISSUE TITLE
Allow bigger sync initialization requests

### ISSUE THREAD

**Issue by skroon** [coddingtonbear/inthe.am#187]
When trying to get started on inthe.am, I encounter the following:
$ task sync init
Please confirm that you wish to upload all your pending tasks to the Taskserver (yes/no) yes
Syncing with taskwarrior.inthe.am:53589

Sync failed.  The Taskserver returned error: 504 Request too big

**Comment by coddingtonbear** [comment]
I bumped up the request limit to a higher size a few hours ago; let me know if that doesn't help!
