### ISSUE TITLE
Add support for contexts

### ISSUE THREAD

**Issue by saerdnaer** [coddingtonbear/inthe.am#197]
see http://taskwarrior.org/docs/context.html for more information

**Comment by coddingtonbear** [comment]
I don't really use contexts personally, but think that such a feature might be nice.  Feel free to have a chat with me on the gitter channel if you'd like to figure out what might be required for creating the feature yourself and posting a pull request.

**Comment by coddingtonbear** [comment]
For the moment, I'm going to close this ticket; let me know if you need help implementing this, @saerdnaer!
