### ISSUE TITLE
Add support for time specification with words

### ISSUE THREAD

**Issue by rominf** [coddingtonbear/inthe.am#204]
Taskwarrior's `due:week` can be easily selected with built-in calendar, but that's not true for `wait:someday`.

**Comment by coddingtonbear** [comment]
Unfortunately, that feature isn't on my roadmap at the moment, but if you do choose to add such a feature and post a pull request, I'll gladly review and merge it. Let me know if you need any help or pointers on how you can add the feature.

Cheers!
