### ISSUE TITLE
Add recurrence duplicate checking functionality

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/inthe.am#213]
Currently, if you have a recurring task and two separate clients create the next recurrence for a given task, both tasks will be preserved, and it can be very confusing.

These tasks are actually very easy to identify; they should:

1. Have identical `(uuid) parent` fields.
2. Have identical `(float) imask` fields.

Should we find a match, we should:

1. Identify which task was created first (hereafter: alpha), and which task(s) were created later (hereafter: beta).
2. Copy all annotations for beta to alpha.
3. Add an annotation to beta identifying the UUID of alpha reading something like "This task duplicated {alpha.uuid} and was deleted."
4. Set a UDA field (perhaps `intheam.duplicateof`) on beta with the UUID of alpha.
5. Delete beta.

We can listen for sync operations and check, in the worst case, all active recurrences to see if there are any active duplicates.

**Comment by BlitzKraft** [comment]
This issue is still present. I am receiving duplicate instances of recurring tasks everytime I sync.

**Comment by coddingtonbear** [comment]
@BlitzKraft -- if you click the "Deduplicate Tasks Now" button, do the duplicates go away?

![image](https://cloud.githubusercontent.com/assets/527661/20448808/a048f1fe-ad9a-11e6-9b73-512142a2e5ca.png)

**Comment by BlitzKraft** [comment]
I haven't tested it yet. I didn't even know this page existed. I will try it out and get back to you.
