### ISSUE TITLE
Dowloaded certificates are actually HTML pages

### ISSUE THREAD

**Issue by demosito** [coddingtonbear/inthe.am#223]
When downloading generated certificates from the site (either from "Getting Started" or from "Configuration & Settings" menu) browser actually downloads HTML pages containing certificate text.
Btw, if you strip out html code and '\n' it works, so certificates are correct.

**Comment by coddingtonbear** [comment]
Thanks for the heads-up, @demosito!  The fix for this was released just a few moments ago.
