### ISSUE TITLE
Application hangs after modifying existing task

### ISSUE THREAD

**Issue by benjaminfvaughn** [coddingtonbear/inthe.am#225]
I've been having a problem since the update from about a week ago. I can create new tasks successfully, but when I modify a task, the application hangs at the loading screen after clicking save. I have noticed this problem on my PC running Chrome and Firefox as well as my Mac running Safari. I can resolve the issue by reloading the page. Immediately after reloading the page, I can usually modify one or two tasks before the application hangs again after clicking save on a new modification.

**Comment by benjaminfvaughn** [comment]
This issue seems to be resolved. I haven't had any of these issues in the last 4 days of usage.

**Comment by coddingtonbear** [comment]
Ahh!  It's probably 0ee3ec6fa2603c7f9f52d2aa172408b16d663ede that fixed it, then; for a while, it was only waiting about a second before giving up on getting a repository lock.  It's fixed now!
