### ISSUE TITLE
saving taskrc yields server error 500

### ISSUE THREAD

**Issue by slabans** [coddingtonbear/inthe.am#226]
Saving an empty Custom .taskrc textfield results in an server error. Error message reads:

> An error was encountered while saving your taskrc settings:
> Server Error (500)

![intheam-taskrc](https://cloud.githubusercontent.com/assets/17641324/14409080/7943a37e-ff0d-11e5-9b9a-caa0545a8480.jpg)

**Comment by coddingtonbear** [comment]
Fixed!
