### ISSUE TITLE
Menu disappears on search

### ISSUE THREAD

**Issue by celador** [coddingtonbear/inthe.am#227]
Whenever I enter anything into the search, on first character, it causes the entire menu with all the tasks to disappear.

**Comment by coddingtonbear** [comment]
I'm not seeing any strange behavior with the search box, @celador -- are you sure there are tasks that match the search you're entering?  [Here's what I see when I try searching](https://youtu.be/_Bq2vD3Lmfc).

**Comment by coddingtonbear** [comment]
Actually -- I just saw this, too; I'm not sure what might've caused it, but thanks for the heads-up!

**Comment by coddingtonbear** [comment]
I haven't seen this in a while and I'm not sure if that's because I fixed it or if it's because I mostly access my tasks via the trello integration.  Could you let me know if this continues to be a thing?
