### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by unixfox** [coddingtonbear/inthe.am#228]
Since the last update, my old tasks have changed color, they are now in red whatever of the task priority. But new tasks are in good color.

Screenshot:
![](https://i.imgur.com/Hbd5EhL.png)

Account name : mimidevos2

**Comment by coddingtonbear** [comment]
Thanks for the heads-up on this, @unixfox -- I'd never have noticed there was something amiss given how many of my tasks are overdue!  This was just a moment ago fixed via 	3b3adbb.

Cheers!
