### ISSUE TITLE
"Could not complete task!" is incorrectly displayed when tasks are marked completed

### ISSUE THREAD

**Issue by MStrohmeier** [coddingtonbear/inthe.am#229]
When marking a task as completed, the "Could not complete task!" error is displayed even if the task is completed successfully. Upon page reload, the completed task is removed from the list despite the appearance of the error. This has occurred in Chrome on both a desktop PC and Android.

**Comment by coddingtonbear** [comment]
Fixed this just a moment ago, @MStrohmeier; thanks for the heads-up!
