### ISSUE TITLE
Syncing back from trello to taskwarrior does not change status

### ISSUE THREAD

**Issue by derphilipp** [coddingtonbear/inthe.am#231]
Moving an item to the "done" field does not change the "Status" of a taskwarrior task,
altough te state of "UDA Orphan intheamtrellolistname" canged to "Done".

I would expect that it is possible to change the state of items via trello. Is this intended otherwise?

**Comment by coddingtonbear** [comment]
That is intended, but I understand why you thought it'd work that way.

The way I handle this is: every morning after my stand-up meetings (during which I'll explain to my team what I've finished), I click on the top of that column and click the "Archive all cards in this list" button.  Archiving a card will cause that task to be marked as completed in Taskwarrior.

**Comment by derphilipp** [comment]
Thank you for your input, I was not aware that archiving the card was necessary to trigger that action.

Thanks for declaring that for me and have a good day!
