### ISSUE TITLE
Tasks with dependencies from Taskwarrior generate errors

### ISSUE THREAD

**Issue by ReedEspinosa** [coddingtonbear/inthe.am#232]
After syncing any tasks that have dependencies from Taskwarrior(v2.5.0), Inthe.AM repeatedly gives me the following error:
> An error was encountered while parsing task 73c4f6cd-a7b4-47a2-b925-e0a60d07e8a2; it was omitted from results as a result: badly formed hexadecimal UUID string.

Afterwards the task containing the dependency is not listed under Tasks inside Inthe.AM. 

I know this is related to issue #92 but I was wondering if it would be easy to simply support tasks with dependencies, even if the dependencies where not displayed inside Inthe.AM.

Thanks!

**Comment by coddingtonbear** [comment]
Tasks having dependencies *are* supported, @ReedEspinosa, even if you can't add/change them using the UI.  The error you're encountering isn't related to #92, but [this upstream Taskwarrior problem](https://bug.tasktools.org/browse/TD-104).

The TLDR is that certain versions of Taskwarrior historically sent improperly-formatted tasks when synchronizing.  This may manifest itself in either the synchronization failing completely, or in dependencies becoming incorrectly formatted.  Additionally, once a broken version of Taskwarrior has synchronized even once, upgrading to the new version of Taskwarrior will not solve the problem without some effort.

Unfortunately, I'm not sure there's a very simple fix.  You could, though, make sure that you're on a non-broken version of Taskwarrior (any version _before_ 2.5.0, or _after_ 2.5.1), click the "Clear Task Data" button in the "Danger Zone" section of Inthe.AM, and re-configure synchronization from the beginning again.

Good luck, though @ReedEspinosa, and let me know if you have any questions or need a hand -- I'm usually online on the gitter.im channel: https://gitter.im/coddingtonbear/inthe.am if you want to chat.

**Comment by ReedEspinosa** [comment]
I upgraded to 2.5.1 and everything is working as expected now. Thanks for the fast response and great software!
