### ISSUE TITLE
Can't get certificates from web

### ISSUE THREAD

**Issue by gokcemay** [coddingtonbear/inthe.am#233]
I follow instructions at https://inthe.am/getting-started 
Get command doesn't work, and  I get: 

> GET /api/v2/user/my-certificate/
> HTTP 401 Unauthorized
> Allow: GET, HEAD, OPTIONS
> Content-Type: application/json
> Vary: Accept
> WWW-Authenticate: Token
> 
> {
>     "detail": "Authentication credentials were not provided."
> }

I can't download .pem files. 
What am I missing?

**Comment by coddingtonbear** [comment]
Whoops!  This is some fallout from a change I released yesterday -- I'll see if I can find a few minutes during PST lunch to fix it up!  In the meantime, you may want to consider using https://github.com/coddingtonbear/taskwarrior-inthe.am to configure sync it _should_ be well-insulated from the bug you're encountering when trying to download the certificate manually.

**Comment by coddingtonbear** [comment]
Fixed just a moment ago, @gokcemay!  Thanks for the heads-up!
