### ISSUE TITLE
Get tasks from API

### ISSUE THREAD

**Issue by waghanza** [coddingtonbear/inthe.am#237]
Hi,

New to intheam, I try to retrieve task list from my account.

I've read the API docs, but a 

~~~sh
curl -H "Authorization: MY_TOKEN" https://inthe.am/api/v2/tasks
~~~

Can I retrieve my task with json or ianother format

Regards,

**Comment by coddingtonbear** [comment]
Hey there @waghanza; I'm not sure I fully understand your question, but, *close* -- to get your task list as JSON, just do something like this:

```
curl -vH "Authorization: Token YOUR_TOKEN" https://inthe.am/api/v2/tasks/
```

Both the trailing slash on the URL and the word 'Token' before your token are important.  Let me know if that doesn't work; cheers!

**Comment by waghanza** [comment]
wrong copy paste (I was using **Token**) keyword

:+1: for end slash (but strange for me :wink: )
