### ISSUE TITLE
Ability to filter tasks by

### ISSUE THREAD

**Issue by skrzepto** [coddingtonbear/inthe.am#238]
Couldn't find a way to do this or find any documentation.

Have the ability to filter tasks by 
* Project
* Status
* Tags

etc....

**Comment by coddingtonbear** [comment]
You can filter in that way by typing into the little search box at the top of your task list.  The filters work very much like those in taskwarrior, so you can filter to a specific project using `project:my-project`, or tags using `+mytag`.

**Comment by skrzepto** [comment]
I'd suggest adding a Usage page in the docs and adding that.

**Comment by coddingtonbear** [comment]
Oh, totally -- feel free to post a pull request adding that, @skrzepto!
