### ISSUE TITLE
Trello mixed up ...

### ISSUE THREAD

**Issue by Ticonderoga** [coddingtonbear/inthe.am#241]
I unfortunately delete Trello list and the sync is not working properly I tried to revoke acces to trello force resync ... nothing seems to work !! How to reset everything ?

**Comment by coddingtonbear** [comment]
Hey there @Ticonderoga -- make sure that you're clicking on the "Trello" link on Inthe.AM after you've refreshed the window.  Part of the resynchronization process involves creating a totally new Trello board for Inthe.AM, so if you're looking at your old one you are looking in the wrong place.

**Comment by coddingtonbear** [comment]
@Ticonderoga -- are you sorted out now, or are you still having trouble with Trello?

**Comment by Ticonderoga** [comment]
still the same ... Trello board not found !! I gave up !!

**Comment by coddingtonbear** [comment]
Alright; well -- let me know if you'd like to give it another shot; we can always hop onto the gitter.im channel to talk it over.

Cheers!
