### ISSUE TITLE
Taskwarrior will not sync when using priority values outside H, M, L

### ISSUE THREAD

**Issue by pierovera** [coddingtonbear/inthe.am#242]
I've already tried adding my .taskrc to the inthe.am website. Here it is:

`uda.priority.values=T,H,M,,L,N`

`urgency.uda.priority.L.coefficient=0.0`

`urgency.uda.priority.N.coefficient=-2.0`

`urgency.uda.priority.T.coefficient=8.0`

If any of my tasks have either the "T" or the "N" priority, it will not sync and will spit out this error: 

```
$ task sync init
Please confirm that you wish to upload all your pending tasks to the Taskserver (yes/no) yes
Syncing with taskwarrior.inthe.am:53589

Sync failed.  The Taskserver returned error: 500 Priority values may be 'H', 'M' or 'L', not 'N'.

```

**Comment by coddingtonbear** [comment]
Yep!  Unfortunately, for the moment Inthe.AM is using a quite-old version of Taskwarrior's Taskserver -- one that doesn't support user-defined priority values.  I have been meaning to upgrade for the last...year or so; maybe I'll try to carve out a little time this weekend to give it another shot!

**Comment by coddingtonbear** [comment]
I've just a moment ago upgraded to Taskserver 1.1; I *think* that'll fix this problem for you.  Let me know if it didn't.

Cheers!
