### ISSUE TITLE
iphone UI broken, can't avoid it

### ISSUE THREAD

**Issue by hymie0** [coddingtonbear/inthe.am#243]
I just started trying out inthe.am

When I go to inthe.am on my iPhone, I get redirected to "Install Inthe.AM on your device".  But the link it installs either crashes every time I open it, or just gives me a blank white page.

But I can't get to any other web interface on my iPhone.  It always redirects me to the "Install" page.

Can you please offer me the option to not use the iPhone-specific page?

**Comment by bobross419** [comment]
I'm experiencing this as well.

When I attempt to access inthe.am I'm redirected to inthe.am/add-to-home-screen

There isn't anything clickable on the screen, so I'm stuck.

ios 10.0.2 (14A456)

Issue is identical in Safari (can't find the version number) and Chrome (53.0.2785.109)

![img_1123](https://cloud.githubusercontent.com/assets/553676/19042322/8d3ccdf2-8959-11e6-8319-6ef252ff83b9.PNG)

**Comment by coddingtonbear** [comment]
Fix released just a little while ago -- thanks for the heads-up @hymie0.

For the record, @bobross419, the button the arrow is pointing at is still there; it's that little square one with the up arrow.
