### ISSUE TITLE
Task Sync fails: Sync failed.  The Taskserver returned error: 500 Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007.

### ISSUE THREAD

**Issue by mani-ramaswamy** [coddingtonbear/inthe.am#248]
When I run a task sync I get the following error:

Sync failed.  The Taskserver returned error: 500 Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007.

It was working as of yesterday, not sure what changed in the Taskserver.

**Comment by coddingtonbear** [comment]
Hey there @mani-ramaswamy -- overnight the VPS I run Inthe.AM on ran out of disk space.  You can recover your account by running [this procedure](https://gitter.im/coddingtonbear/inthe.am?at=57ed815cb0ff456d3ad0bdf4).

1. Make sure that your local clone has all of the tasks you want. This is probably a given, but given the next few steps, you'll see why I'm calling that out explicitly.
2. Click the "Clear Task Data" button in the "Danger Zone" section of your Inth.AM configuration (https://www.dropbox.com/s/u11vnfs201f4tgp/Screenshot%202016-09-29%2014.04.33.png?dl=0)
3. Using your local taskd client, run `task sync init`

That should get things back into order.  Good luck!

**Comment by mani-ramaswamy** [comment]
Thanks for the super prompt response, that fixed it.
