### ISSUE TITLE
Add google fit sync

### ISSUE THREAD

**Issue by seniorivn** [coddingtonbear/inthe.am#249]
Hi i think it could be interesting, we could add google fit sync feauture and possibility to create rules, matching fit data to the actual tasks. like every day running, could be set done automatically.

**Comment by coddingtonbear** [comment]
Hey there @seniorivn -- that sounds like something a tool like Bugwarrior might be better-equipped to handle than Inthe.AM.  Really, Inthe.AM's goal is just to be a tool you use for interacting with your existing task list; Bugwarrior, though, is really designed to make it easy for you to create and update tasks in your task list via synchronizing with other third-party services.

Feel free to propose this idea on their issue tracker! 

Cheers!

**Comment by seniorivn** [comment]
@coddingtonbear thanks, for the advice, i'll go to the bugwarrior.
