### ISSUE TITLE
iphone -- fields lose focus after one character

### ISSUE THREAD

**Issue by hymie0** [coddingtonbear/inthe.am#257]
On my iPhone, when I create a new task...

When I select the "Tags" field, I can type one character; then the field loses focus, and I must re-select the "Tags" field to continue typing.

When I select any of the various Date fields, I can type one character (usually a "2" to start my date); then the field immediately populates itself with "0001-12-31 19:00" and loses focus.  Then I must re-select the field, erase the incorrect data, and finally type my date.

**Comment by coddingtonbear** [comment]
Would you mind posting a PR for that with a fix, @hymie0?  I have very little time available to allow to Inthe.AM and without your help, it might be months before I get to that.

**Comment by coddingtonbear** [comment]
Good news, @hymie0 -- the UI is all just Javascript!

**Comment by hymie0** [comment]
Another language I don't know, but again, I'll try to take a look.

**Comment by coddingtonbear** [comment]
Well; if you need any help -- I'm usually in the gitter.im channel, and I'd be glad to help you out with any questions.

**Comment by zenware** [comment]
Can someone re-confirm this issue? If not I'll investigate in an emulator when I'm home from work

**Comment by hymie0** [comment]
I am still having the problem on my iPhone.  I try to create a new task, I
select the "Due" field, and type the character "2".  The field immediately
fills with "0001-12-31 19:00" and loses focus.  Same happens with the
"Wait" and "Scheduled" fields.  In each case, I am required to select
the field again, erase all of the text in the field, and only then can I
type in the date I wanted to type.

--hymie!

**Comment by coddingtonbear** [comment]
Oh, there have been so many UI changes over the last month; I assume this is now resolved.  Cheers!
