### ISSUE TITLE
Filtering by tag does not seem to work

### ISSUE THREAD

**Issue by tjstankus** [coddingtonbear/inthe.am#258]
I've tried filtering the task list by `+tagname` and `tagname`, neither of which appear to work. Am I doing something wrong?

**Comment by coddingtonbear** [comment]
Ahh; it looks like that's the source of this sentry error --

* http://sentry.adamcoddington.net/share/issue/322e31343634/

**Comment by coddingtonbear** [comment]
Fix released!
