### ISSUE TITLE
bugwarrior github.include_repos doesn't seem to work

### ISSUE THREAD

**Issue by tnguyen14** [coddingtonbear/inthe.am#259]
I use the `github.include_repos = project_foo,project_foz` setting for bugwarrior to only include a certain number of repos. However, this property doesn't seem to have any effect, as issues from all repos are being pulled in for me?

**Comment by coddingtonbear** [comment]
Currently Inthe.AM uses a variant of v1.1.3 of bugwarrior; can you confirm that behaves properly if you use a more-modern version of bugwarrior locally?

**Comment by tnguyen14** [comment]
It seems that the feature was included in v1.4.0 https://github.com/ralphbean/bugwarrior/commit/265683b780f2831b4181f8b2bf3788fd3cc3d61c

**Comment by tnguyen14** [comment]
how difficult do you think it would be to upgrade the bugwarrior version from 1.1.3 to the latest?

**Comment by coddingtonbear** [comment]
Definitely not insurmountable, but it would take some effort; feel free to try!  Inthe.am runs bugwarrior via [this function](https://github.com/coddingtonbear/inthe.am/blob/development/inthe_am/taskmanager/bugwarrior_adapter.py#L21) which is very similar to one that already exists in the bugwarrior codebase.  Assuming there aren't any significant API changes, it might be a simple drop-in replacement; if there _were_ any API changes you might be in for an adventure.

**Comment by coddingtonbear** [comment]
I'm afraid I'm planning on discontinuing built-in bugwarrior support sometime in the next week or so; so bugwarrior is very unlikely to be updated.
