### ISSUE TITLE
bugwarrior cron job

### ISSUE THREAD

**Issue by tnguyen14** [coddingtonbear/inthe.am#260]
Would it be possible to enable a cron job for bugwarrior, so I don't have to manually re-sync to update the tasks? Or maybe this is already built in? https://bugwarrior.readthedocs.io/en/latest/using.html#cron

**Comment by coddingtonbear** [comment]
Not on the site -- it's just a little beta feature at the moment and would need a bit more polish in other areas before getting to such a change, but you [*can* trigger using the `taskwarrior-intheam` tool's (undocumented) `sync_bugwarrior` subcommand](https://github.com/coddingtonbear/taskwarrior-inthe.am).  If you were looking to wire such a sync up to your own cron job, you could use that, or examine the above repo to glean what API endpoints are being hit.

In _the future_, the sync_bugwarrior command will be documented here: http://intheam.readthedocs.io/en/latest/api/endpoints.html, but at the moment none of the beta features are documented.  Sorry about that!

**Comment by tnguyen14** [comment]
Ok no problem. I'll try and see if I can run bugwarrior locally for now. How should I go about removing bugwarrior integration?

**Comment by coddingtonbear** [comment]
Oh, sorry -- I may have miscommunicated a little.  Although you can *totally* run bugwarrior locally if you want, you don't _need_ to do that to use the instructions I gave you above.  What the above instructions let you do is run a local script that will tell Inthe.AM itself to run bugwarrior for you.  That being said -- if you do really want to run bugwarrior locally, you can clear out your bugwarrior configuration by just emptying the bugwarrior configuration field on your configuration page.

**Comment by tnguyen14** [comment]
Ah I see. I can just run the local script to get Inthe.AM to run bugwarrior then. Should I just copy the commands.py file you reference earlier and run that in my cron job?

**Comment by coddingtonbear** [comment]
Oh; you shouldn't need to copy/paste anything; just install the module by running

```
pip install taskwarrior-inthe.am
```

Then, run the command that tells the application you just installed to tell Inthe.AM to sync with bugwarrior --

```
intheam sync_bugwarrior
```

The first time you run it, it will ask you for your Inthe.AM API key; you can find it in the "API Access" section of the "Configuration" page of your Inthe.AM account.  After you've run it once and answered `Y` when it asked you whether it should save the credentials you've provided, it won't ask for your API key again, so cron will be able to run it on your behalf using the API key it saved.

**Comment by tnguyen14** [comment]
Thanks! I am getting the following error when running it:

```shell
:; intheam sync_bugwarrior
usage: intheam [-h] [--config CONFIG] [--taskrc TASKRC] [--loglevel LOGLEVEL]
               {setup,clear_passwords}
intheam: error: argument command: invalid choice: 'sync_bugwarrior' (choose from 'setup', 'clear_passwords')
```

Here's the version it downloaded
```shell
:; pip install taskwarrior-inthe.am
Collecting taskwarrior-inthe.am
  Downloading taskwarrior-inthe.am-0.1.1.tar.gz
```

**Comment by coddingtonbear** [comment]
Whoops; I guess I haven't released the version with the `sync_bugwarrior` command.  If you install from the github repository, you should be good-to-go, though!  If you've never done something like that, you'll probably want to first uninstall taskwarrior-inthe.am by running:

```
pip uninstall taskwarrior-inthe.am
```

then install the version on github with:

```
pip install -e git+http://github.com/coddingtonbear/taskwarrior-inthe.am@master#egg=taskwarrior-inthe.am
```

**Comment by tnguyen14** [comment]
I was able to run it manually, and after the first run, it did not ask for the API key anymore. However, when putting it in the cronjob, I get this error. Do you know what might be wrong?

```shell
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Please enter your API key: (Input hidden) Traceback (most recent call last):
  File "/usr/local/bin/intheam", line 9, in <module>
    load_entry_point('taskwarrior-inthe.am', 'console_scripts', 'intheam')()
  File "/Users/tri.nguyen/dotfiles/src/taskwarrior-inthe.am/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/Users/tri.nguyen/dotfiles/src/taskwarrior-inthe.am/taskwarrior_inthe_am/commands.py", line 191, in sync_bugwarrior
    api = get_api_connection(config)
  File "/Users/tri.nguyen/dotfiles/src/taskwarrior-inthe.am/taskwarrior_inthe_am/api.py", line 38, in get_api_connection
    "Please enter your API key: (Input hidden) "
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
```

**Comment by coddingtonbear** [comment]
Hrm; it looks like when it's running in your cronjob, it can't access your keychain, and is attempting to ask for your password while the cronjob is being executed.  I don't have an easy workaround for you at the moment, but you could just `POST` to the API endpoint directly using curl.  The URL you'd want to `POST` to is `https://inthe.am/api/v2/tasks/bugwarrior/sync/`; just make sure you add the right authorization headers (described in Inthe.AM's API docs).

**Comment by tnguyen14** [comment]
Ok thanks. I just tried it with
```shell
curl -X POST -H "Authorization: Token apitoken" https://inthe.am/api/v2/tasks/bugwarrior/sync/```

Is there a way to know if it works? I don't see any response.

**Comment by coddingtonbear** [comment]
As long as you received a 200 HTTP status code, you're good-to-go!

**Comment by tnguyen14** [comment]
Cool. I think I got a `202 ACCEPTED`

**Comment by coddingtonbear** [comment]
Yep; that's perfect.

**Comment by tnguyen14** [comment]
Thanks very much for your help!

**Comment by coddingtonbear** [comment]
No problem; good luck!
