### ISSUE TITLE
Urgency and nested projects

### ISSUE THREAD

**Issue by dalai4git** [coddingtonbear/inthe.am#263]
Configuring the urgency of projects like Home.Kitchen and Home.Garden (taken from the examples in taskwarrior.org) does not work.

This does not do anything, but works fine on the cli

    urgency.user.project.home.kitchen.coefficient=99

This does work but moves everything in home up

    urgency.user.project.home.coefficient=99

**Comment by coddingtonbear** [comment]
Fix released!  You'll have to go into your settings and re-save your configuration for the new filter rules to be applied, but after that, you should be OK.  Let me know if that doesn't help!
