### ISSUE TITLE
getting a 502 bad gateway message

### ISSUE THREAD

**Issue by Weej1** [coddingtonbear/inthe.am#267]
Hi I've been using inthe.am for sometime now and recently I started getting a message saying
Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver

I visited the site and saw that I'm getting a 502 Bad gateway message appear on the right of the screen (with nginx 1.8.something showing up) Is this an error or just that the site is being closed down?

**Comment by 4kbt** [comment]
All of my connections have been down today. Errors vary between machines and Android app. In addition, the web interface shows an expired certificate.

**Comment by coddingtonbear** [comment]
A couple members' task repositories had grown to several GB in size.  I've taken care of some pruning, but had to take down the taskserver (and, thus, the UI) while it was taking place in order to prevent people from accidentally corrupting their task lists.  Everything should be up now, though!

**Comment by 4kbt** [comment]
Web app is back up.

Desktop sync fails: 

$ task sync
Syncing with taskwarrior.inthe.am:53589

Sync failed.  The Taskserver returned error: 500 Unrecognized taskwarrior file format. at line 720


Android Taskwarrior app sync fails: 

Failed to connect to local socket: Unknown error: -1

Sync failed. Could not connect to the Taskserver.


Both sync methods worked yesterday. Another desktop threw a slightly different 500-series (I think) error this morning.

Thank you!

**Comment by coddingtonbear** [comment]
@4kbt -- could you PM me your `taskd.credentials` setting from your `~/.taskrc` on Gitter?  With that, I can have a look at your taskserver data to see if there's something amiss.

**Comment by 4kbt** [comment]
PM sent.

**Comment by 4kbt** [comment]
Just got back to my home machine, where the error is different:

$ t sync
Syncing with taskwarrior.inthe.am:53589

Sync failed.  The Taskserver returned error: 500 Client sync key not found.

Again, all three of these have worked for weeks :).

**Comment by coddingtonbear** [comment]
Try again now, @4kbt

**Comment by 4kbt** [comment]
Interesting. One out of three works. The one with the "at line 720" error works.

The Android app and the "Client sync key"  desktop does not.

**Comment by coddingtonbear** [comment]
I'm afraid I don't have any ideas about how to help you with your Android app; your only option might just be to clear the android app and re-synchronize as if it were a new client.  Good luck!

**Comment by 4kbt** [comment]
Both desktops are now syncing correctly after a little bit of sync / sync init fiddling. Android trouble looks unrelated to the server problem. Thank you!
