### ISSUE TITLE
Rounding the priority results in a different task order

### ISSUE THREAD

**Issue by Ippo343** [coddingtonbear/inthe.am#269]
I see that the web interface is rounding* the priority of the tasks in the list.
This is apparently done before sorting the list, which results in a different task order than that of the desktop client which sorts them without rounding the priority.

Example: suppose you have three tasks, A, B, and C with a priority of 6.3, 6.2 and 6.1 respectively.
The command line task program will list them as A, B, C in descending order of priority.
However, inthe.am will display them out of order because everyone of them has a priority of 6 according to the web interface.

* In my task list all the priorities are being rounded down, but I have no task that would be rounded up, so I'm not sure if it is taking the floor of the priority or actually rounding it.

**Comment by davisdude** [comment]
I can confirm that it is rounding down, causing tasks to be incorrectly sorted.

**Comment by coddingtonbear** [comment]
I looked into this a little, and it appears that this is actually an upstream problem in `taskw` -- I've filed this as a bug there.  Cheers & thanks.
