### ISSUE TITLE
Make it possible to use Trello's Custom Fields power-up to dispay more task info

### ISSUE THREAD

**Issue by harleypig** [coddingtonbear/inthe.am#270]
Trello has a power-up called Custom Fields that seems would be useful for displaying more task information, especially project, created, started, scheduled and dependencies.

I took a quick look through the code, but I don't know python well enough to see how this would be done.

**Comment by coddingtonbear** [comment]
I can't imagine how I'd ever find the time to get to this; so for the moment, I'm going to close this given that there's no conceivable way that this would get done.

Definitely reach out if you're willing to take on the development of this, though!

Cheers!
