### ISSUE TITLE
Custom port option

### ISSUE THREAD

**Issue by Trial-In-Error** [coddingtonbear/inthe.am#271]
Hello!

I can't sync to inthe.am on some networks; in a [previous issue](https://github.com/coddingtonbear/inthe.am/issues/109), it was mentioned that this port might be blocked. Would it be possible to allow users to customize the port used, or offer an additional port in a more normal range?

Thanks tons for such a useful part of my daily organizing :)

**Comment by coddingtonbear** [comment]
I'm afraid not, @Trial-In-Error!  All users share a single taskd server, so, there's really no easy way to make the port configurable. 

If I were you and wanted to route synchronization through a different port, I'd set up a port forward via an SSH tunnel somewhere!  If you have a VPS already, that's the perfect place for that sort of thing.

Cheers & good luck!

**Comment by MartyLake** [comment]
Hey @Trial-In-Error , did you manage to configure it somehow ? :)

**Comment by coddingtonbear** [comment]
@MartyLake -- is it instructions for forwarding a port through a VPS that you're looking for, or were you looking for some other kind of answer?  If it's just port forwarding, you can refer to this documentation: https://www.ssh.com/ssh/tunneling/example

**Comment by MartyLake** [comment]
I am looking for instructions on how to do the vps trick, with an aws
lambda maybe?

Le lun. 24 juin 2019 à 19:08, Adam Coddington <notifications@github.com> a
écrit :

**Comment by Trial-In-Error** [comment]
I have not put any more effort into this! If anyone else has a solution, please let me know. :)

**Comment by coddingtonbear** [comment]
The instructions for doing this on a VPS are what I've linked earlier.  All you need is some node on the internet that itself can connect to Inthe.AM and you are able to SSH into.  Then just look at the port tunnelling examples https://www.ssh.com/ssh/tunneling/example

**Comment by MartyLake** [comment]
I don't have any node on the internet right now. Will try that on a RaspberryPi as soon as I have internet installed at home (next month if O2 wants to).

I suppose the taskwarrior data exchange is not comparable to HTTP and cannot be emulated on a free-tier aws lambda ?

**Comment by MartyLake** [comment]
Would it be possible to have a local server that routes all the taskwarrior sync traffic into the inthe.am rest api ? :) that would effectively solve the problem of ports blocking for me.

**Comment by coddingtonbear** [comment]
There's an American saying: "Anything is possible with enough time and money." You could probably write something that could translate the most important parts of what `task sync` does into Inthe.AM's REST requests with a month or so of effort and zero dollars.

Alternatively, you could spend [€2.49/month](https://www.hetzner.com/cloud) ([other options here](https://www.techradar.com/news/cheap-vps-hosting-deals)) for a VPS you can use for many things including forwarding your sync requests through.  In such a case, it'd probably take you about an hour for you to get your VPS set up with an SSH server you can use for forwarding through.
