### ISSUE TITLE
done tasks get archived in trello

### ISSUE THREAD

**Issue by kattenhund** [coddingtonbear/inthe.am#289]
Marking a task done in taskwarrior removes that card from the trello board. Would be preferred if one could use a hook script to move it to the Done-list

**Comment by coddingtonbear** [comment]
I'm afraid I'm a little hesitant about adding that kind of behavior!  Currently "completed" tasks ignored by most everything, and changing that behavior would be complicated and require a ton of testing and troubleshooting.  I'm not likely to have the time to add a feature like that in the foreseeable future, but if you were wanting to take on that kind of a challenge, I'd be willing to talk  you through what a pull request adding that kind of functionality might look like, and what kind of testing you might need to do to verify that things aren't broken.

**Comment by kattenhund** [comment]
Trying the service to organize bs thesis work, so afraid I wont have the time... will hopefully be able to in the future though :)

**Comment by coddingtonbear** [comment]
Cool -- well, if you _do_ end up finding the time to work on such a thing, feel free to message me on the gitter channel, and I'll be glad to have a conversation about that; we can re-open this issue then!

Cheers!
