### ISSUE TITLE
"The specified session has been invalidated for some reason"

### ISSUE THREAD

**Issue by sanjayankur31** [coddingtonbear/inthe.am#292]
Hello,

I'm getting this error on this machine this morning. I've accepted the new TOS etc already, albeit that was on a different machine. To be sure that I hadn't any corrupted data, I moved the data files to a folder and tried to re-do the whole sync.

```
$ task synchronize init
Please confirm that you wish to upload all your pending tasks to the Taskserver (yes/no) yes
c: 1 Received packet with illegal length: 16560
Syncing with taskwarrior.inthe.am:53589

The specified session has been invalidated for some reason.
Sync failed.  Could not connect to the Taskserver.
```

Any ideas? 
Cheers! :)

**Comment by sanjayankur31** [comment]
Hrm, can't use it via the webinterface either. I keep getting "Your task list is currently in use, please try again later" errors.

**Comment by coddingtonbear** [comment]
Could you let me know what e-mail address you're using for logging-in; either post it here, or send it to support@inthe.am and I can dig it up in my e-mail?

**Comment by sanjayankur31** [comment]
Hello, it's: sanjay DOT ankur AT gmail DOT com.

Thanks :)

**Comment by sanjayankur31** [comment]
I just got home and double checked - I can sync with the machine here just fine. It's only the other machine that seems to have trouble somehow.

**Comment by coddingtonbear** [comment]
I'd _guess_ that maybe your second computer is behind some kind of firewall; usually I've just had a look at your account, and everything looks fine.  🤷‍♂️

**Comment by coddingtonbear** [comment]
The "Your task list is currently in use" message is perfectly normal to see from time-to-time; during any operation that changes your task list, we lock the task list to ensure that there isn't data corruption.  During that time, any other changes to your task list will cause that message to be displayed.

**Comment by sanjayankur31** [comment]
Thanks for checking it up. The other machine is at universitiy, so it certainly is possible that the university IT folks changed something (the do love tinkering and breaking things). It used to work just fine. I'll run more checks etc when I get in next week. I'll leave this open in the meantime.

**Comment by coddingtonbear** [comment]
If you happen to have a VPS or another host you can access remotely (and your university hasn't blocked SSH access) one option people commonly do is tunnel connections through ssh.  Check out the docs here ["Unable to use port 53589"](https://taskwarrior.org/docs/taskserver/troubleshooting-sync.html) if you wanted to give that a shot.

**Comment by coddingtonbear** [comment]
I'm going to assume that you sorted this out, @sanjayankur31, since I haven't heard back from you in a while.  If you are still running into trouble, though, totally feel free to send me a message on the gitter channel.

**Comment by rominf** [comment]
I have exactly the same issue, please reopen:
```
$ task sync init
Please confirm that you wish to upload all your pending tasks to the Taskserver (yes/no) yes
c: 1 Received packet with illegal length: 16480
Syncing with taskwarrior.inthe.am:53589

The specified session has been invalidated for some reason.
Sync failed.  Could not connect to the Taskserver.
```

**Comment by coddingtonbear** [comment]
I'm afraid, @rominf, that that kind of problem indicates that there is some sort of firewall between your PC and the taskserver.  If you can find additional information that shows that not to be the case, or have any data that isn't noted here or on the current open issue (#301), I'd be interested in seeing it, though!
