### ISSUE TITLE
constant connection errors

### ISSUE THREAD

**Issue by 0atman** [coddingtonbear/inthe.am#295]
Since about 2 weeks ago, I've gotten many `handshake` and `connect` errors when trying to sync. These errors often require multiple sync attempts to clear, which is really slowing down my flow.

What's happening, capacity issues? Can I help with hosting etc costs?

Here's an example just now of it taking 5 tries to sync:

```shell
λ until task sync; do sleep 1; done
Syncing with taskwarrior.inthe.am:53589

Handshake failed.  Error in the pull function.
Sync failed.  Could not connect to the Taskserver.
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
Syncing with taskwarrior.inthe.am:53589

Sync successful.  2 changes uploaded.
```

Thank you for a fantastic service otherwise!

**Comment by 0atman** [comment]
I've tried now that I'm home, and it works fine - I bet it's something weird with my work connection - sorry to bother you!

**Comment by coddingtonbear** [comment]
No worries at all; cheers!
