### ISSUE TITLE
migrate from tlslite to tlslite-ng

### ISSUE THREAD

**Issue by tomato42** [coddingtonbear/inthe.am#297]
[`tlslite`](https://github.com/trevp/tlslite) is effectively abandoned (no new commits for 3 years); migrate to [`tlslite-ng`](https://github.com/tomato42/tlslite-ng) as it is maintained and developed (yearly releases)

I'm the primary developer of tlslite-ng and former main contributor to tlslite.

**Comment by coddingtonbear** [comment]
Good idea!  You might've noticed that that's only a transitive dependency of inthe.am; you happen to have a notion of which of inthe.am's deps might be the actual repo that could make that kind of change?

**Comment by tomato42** [comment]
no, haven't analysed it and nothing "jumps" at me as a culprit, sorry

in theory, the tlslite-ng package has `obsoletes=["tlslite"]` so it may be sufficient to met the dependencies of the other packages, but I never actually tested it...

one way to see what depends on it, may be to uninstall tlslite, remove it from requirements.txt and asking pip to install everything; either the removal will fail because something depends on it, or the install will tell what depends on it while installing

**Comment by coddingtonbear** [comment]
This appears to have been a long-removed transitive requirement via `jira` --

```
jira==0.47
  - ordereddict [required: Any, installed: 1.1]
  - requests [required: >=2.6.0, installed: 2.25.0]
    - certifi [required: >=2017.4.17, installed: 2019.11.28]
    - chardet [required: >=3.0.2,<4, installed: 3.0.4]
    - idna [required: >=2.5,<3, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.25.8]
  - requests-oauthlib [required: >=0.3.3, installed: 1.3.0]
    - oauthlib [required: >=3.0.0, installed: 0.7.2]
    - requests [required: >=2.0.0, installed: 2.25.0]
      - certifi [required: >=2017.4.17, installed: 2019.11.28]
      - chardet [required: >=3.0.2,<4, installed: 3.0.4]
      - idna [required: >=2.5,<3, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.25.8]
  - requests-toolbelt [required: Any, installed: 0.9.1]
    - requests [required: >=2.0.1,<3.0.0, installed: 2.25.0]
      - certifi [required: >=2017.4.17, installed: 2019.11.28]
      - chardet [required: >=3.0.2,<4, installed: 3.0.4]
      - idna [required: >=2.5,<3, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.25.8]
  - six [required: >=1.9.0, installed: 1.14.0]
  - tlslite [required: >=0.4.4, installed: 0.4.9]
```

the Jira library hasn't been installed in quite some time now that Bugwarrior support was dropped.  I think this is closable now.

Cheers!
