### ISSUE TITLE
Isn't the secret key supposed to be secret?

### ISSUE THREAD

**Issue by MathiasSM** [coddingtonbear/inthe.am#299]
https://github.com/coddingtonbear/inthe.am/blob/347163a212d6fa00c10c2701d41a47b290e9ca95/inthe_am/settings.py#L29

**Comment by coddingtonbear** [comment]
Whether or not there is a defined secret key in this repo to aid in folks setting up a development environment, doesn't mean it isn't overridden in production (and it is, but you're welcome to try it out, though ;-) if you don't believe me).
