### ISSUE TITLE
500 Server Error when logging in with Google for first time

### ISSUE THREAD

**Issue by Towerism** [coddingtonbear/inthe.am#302]
Never used taskwarrior or inthe.am until today. Tried to login with Google (I have never logged in to inthe.am before), and I am greeted with a white page that just says "Server Error (500)"

**Comment by coddingtonbear** [comment]
Actually; restarting the service wasn't going to fix the issue; I've started a process that should fix everything up and will post here in a few minutes once things are recovered.

**Comment by coddingtonbear** [comment]
Should be OK now, @Towerism / @komidore64; give it a shot now!

**Comment by Towerism** [comment]
@coddingtonbear I was able to log in!

**Comment by coddingtonbear** [comment]
Awesome; I'm glad to hear that.

**Comment by komidore64** [comment]
@coddingtonbear looks good! thanks so much!

**Comment by codekoala** [comment]
I've been getting this 500 error for several weeks. I can still sync just fine, but I can't log into the actual web UI using my Google account. Do you see any recent 500 errors in your logs that can help resolve this again?

**Comment by coddingtonbear** [comment]
I do, in fact, see an error in my logs about somebody having trouble logging-in:

```
ERROR:sentry.errors.uncaught:2018-11-21 20:44:34,612 base 15631 -144668224 [u'Session value state missing.']
ERROR:sentry.errors.uncaught:2018-11-21 20:44:34,618 base 15631 -144668224 [u'AuthStateMissing: Session value state missing.', u'  File "django/core/handlers/base.py", line 132, in get_response', u'  File "django/views/decorators/cache.py", line 57, in _wrapped_view_func', u'  File "django/views/decorators/csrf.py", line 58, in wrapped_view', u'  File "social_django/utils.py", line 49, in wrapper', u'  File "social_django/views.py", line 33, in complete', u'  File "social_core/actions.py", line 41, in do_complete', u'  File "social_core/backends/base.py", line 40, in complete', u'  File "social_core/utils.py", line 252, in wrapper', u'  File "social_core/backends/oauth.py", line 388, in auth_complete', u'  File "social_core/backends/oauth.py", line 90, in validate_state']
ERROR:django.request:2018-11-21 20:44:34,619 base 15631 -144668224 Internal Server Error: /complete/google-oauth2/
Traceback (most recent call last):
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_core/actions.py", line 41, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_core/utils.py", line 252, in wrapper
    return func(*args, **kwargs)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_core/backends/oauth.py", line 388, in auth_complete
    state = self.validate_state()
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/social_core/backends/oauth.py", line 90, in validate_state
    raise AuthStateMissing(self, 'state')
AuthStateMissing: Session value state missing.
ERROR:sentry.errors.uncaught:2018-11-21 20:44:34,626 base 15631 -144668224 [u'Internal Server Error: /complete/google-oauth2/', u'  File "django/core/handlers/base.py", line 132, in get_response', u'  File "django/views/decorators/cache.py", line 57, in _wrapped_view_func', u'  File "django/views/decorators/csrf.py", line 58, in wrapped_view', u'  File "social_django/utils.py", line 49, in wrapper', u'  File "social_django/views.py", line 33, in complete', u'  File "social_core/actions.py", line 41, in do_complete', u'  File "social_core/backends/base.py", line 40, in complete', u'  File "social_core/utils.py", line 252, in wrapper', u'  File "social_core/backends/oauth.py", line 388, in auth_complete', u'  File "social_core/backends/oauth.py", line 90, in validate_state']
```

Looking at this long thread https://github.com/omab/python-social-auth/issues/534, that could be any number of things.  Since I'm able to log-in and yours is the only report, I'm assuming that this is on the client side.  You wouldn't happen to be trying to log-in with Safari, would you, @codekoala (context: https://github.com/omab/python-social-auth/issues/534#issuecomment-436832324)?

**Comment by codekoala** [comment]
No, I was attempting to login with Chrome. I just attempted to login using Firefox, Opera, and a new private window in Chrome. All attempts resulted in the Error 500.

**Comment by codekoala** [comment]
It worked! Thank you!

**Comment by seonwoolee** [comment]
I attempted to log into inthe.am for the first time, and I got this error. I tried it with both Firefox and Google Chrome

**Comment by seonwoolee** [comment]
Hmmm it definitely wasn't working yesterday but it's working today.

**Comment by krzyklo** [comment]
Hi  CodingtonBear, 
I am trying to register with the Google, and I am getting 500 Server Error when trying to login first time. 

I've seen some of this kind of problems on the forum, but no solutions other than your server side modifications. 

Tried to log in from a few Google accounts, over the span of two days, with different web browsers: Firefox/Chrome. 
Always the 500 Servor error. 
How I could assist in figuring out what is wrong?

**Comment by jonathanbcarlson** [comment]
Hi @coddingtonbear,

I already have an account with inthe.am but after signing in I immediately get `Server Error (500)` under `google-oauth2`.

Any ideas on why this is happening?
Thanks for all the work you do inthe.am!
