### ISSUE TITLE
Bugwarrior integration will be discontinued on 15 December 2018

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/inthe.am#303]
Bugwarrior is a fantastic tool, and three years ago a built-in Bugwarrior integration was added as Beta feature to help users more easily use it with their task list.  Unfortunately, this feature has been very lightly used, and requires a significant amount of continuing investment to maintain; so it will be discontinued on 15 December 2018.

Good news, though -- bugwarrior is very easy to run outside of Inthe.AM: to find out how, check out [Bugwarrior's documentation](https://bugwarrior.readthedocs.io/en/latest/).

As always, thanks for your understanding, and feel free to reach out if you happen to be one of the few folks using Bugwarrior with Inthe.AM and need a hand setting up Bugwarrior locally.

Cheers,
Adam

**Comment by asm0dey** [comment]
Will I still be able to sync my bugwarrior tasks?

**Comment by coddingtonbear** [comment]
Yes of course, @asm0dey; I, too, will be continuing to use bugwarrior -- just running it locally instead of on Inthe.AM.

**Comment by asm0dey** [comment]
@coddingtonbear thank you for info! Even didn't know that it's possible to run bugwarrior in any other way :-)

**Comment by coddingtonbear** [comment]
Removed in 30b4c73c037e5883e206cea39e63ad59cc0dc97a, 11b60f019e23f0e0614d20751c7b6f6664221f1a, and f35882de59a009c9c5b214ad0cced4db75ba406c.
