### ISSUE TITLE
Created task on trello does not appear on TW

### ISSUE THREAD

**Issue by MartyLake** [coddingtonbear/inthe.am#304]
Hello,

When I create a task in Trello, it does not create it in TW. Is this the intended behavior ? My usecase was to use Trello on mobile as inbox and later on computer use intheam-web or tw-cli to process these tasks.

Best,

**Comment by coddingtonbear** [comment]
It should as long as you're creating that task on the board named "Inthe.AM Tasks".  It isn't immediate, of course, but you should see the task appear on your task list on Inthe.AM within a few minutes of it being added on Trello.

**Comment by MartyLake** [comment]
It's on the good board, but new cards are not being created back to intheam
ever hours after :(

Le jeu. 22 nov. 2018 à 19:39, Adam Coddington <notifications@github.com> a
écrit :

**Comment by coddingtonbear** [comment]
Hrm; I'm not exactly sure what might be amiss; one thing you could try is:

1) Clicking the "Reset Trello Settings" button from the configuration page on Inthe.AM.
2) In trello, deleting the board named "Inthe.AM Tasks"
3) Re-enabling trello from your Inthe.AM configuration page.

**Comment by MartyLake** [comment]
After doing your procedure, the task I created at first trial reappeared.

Then I understood: the search in intheam (and probably TW?) is case sensitive ! I used the word "TRELLO" to create my test task i trello, and did not yield any result when I searched for "trello" in the intheame search bar.

False positive then.

**Comment by MartyLake** [comment]
Thanks for your support !!!

**Comment by coddingtonbear** [comment]
No problem; good luck!
