### ISSUE TITLE
Calendar views

### ISSUE THREAD

**Issue by linuxcaffe** [coddingtonbear/inthe.am#31]
It would be great to be able to look at dated tasks in weekly, monthly or daily (agenda) calenders, extra points for drag and drop.

**Comment by coddingtonbear** [comment]
At the moment this isn't likely to ever make it onto the roadmap; if you'd like to add such a feature, though, I'd be glad to review/merge your work.  Let me know if you need any pointers on how to get a pull request put together, though!

Cheers,
Adam
