### ISSUE TITLE
Server Error message displayed on first log-in

### ISSUE THREAD

**Issue by shawntan** [coddingtonbear/inthe.am#312]
I'm encountering this error no matter how I sign into the site:

Error
An error was encountered while attempting to gather user information:
Server Error (500)

**Comment by coddingtonbear** [comment]
I'm not having any trouble at the moment :man_shrugging:

**Comment by shawntan** [comment]
Thanks for the quick response! What kind of additional information do you need?

1. I was trying to sign up with a Google account, and this is how I encountered the error.
2. When I check the XHR requests, there are two requests to `tasks/` and `status/`, which both come back with:
 ```
 <h1>Server Error (500)</h1>
 ```

**Comment by coddingtonbear** [comment]
I've just pushed up a change that'll upgrade the library used for authentication to the latest version -- it does look like the library I am using did until recently depend upon features of Google+ that were recently discontinued (see more information here, if you're curious: https://developers.google.com/+/api-shutdown).  If you could give it a shot now, I'd be curious to hear if that fixed your problem.

**Comment by bandita00** [comment]
The problem is the same for me, even after the latest commit.

**Comment by coddingtonbear** [comment]
I've just checked this locally using an account I just generated, and _do_ see the error you've mentioned.  What I also see, though, is that if you just refresh the page (or log out and in), it will load correctly. Maybe try that for now; it should only affect your first log-in.

**Comment by coddingtonbear** [comment]
OK; the underlying problem has now been fixed.

**Comment by shawntan** [comment]
Sorry I couldn't reply earlier, but yes! It's been fixed.

Thanks!
