### ISSUE TITLE
Support other authentication options, cf. indielogin.com

### ISSUE THREAD

**Issue by johanbove** [coddingtonbear/inthe.am#314]
Have you considered integration authentication with https://indielogin.com/api yet?

I don't want to log in using Google and I am willing to lose out on integrations (cf Trello), if these are intertwined with the Google account, if I could log into https://inthe.am using Web Sign or one of the other cool sign in options provided by Web Sign-in. 

More info: https://indieweb.org/Web_sign-in

**Comment by coddingtonbear** [comment]
I'm afraid I really have to keep things as simple as possible for now (see https://github.com/coddingtonbear/inthe.am/issues/251 for the last time this was asked about); unfortunately I don't have a ton of time to devote to this project, and every extra option added adds its own permanent maintenance burden.  At the moment, I'm just barely able to find the time to keep the site running at all. Maybe if I had some more folks available to help out with maintenance, though, I'd be willing to consider such things in the future!

Just to let you know, though, if you were to run this on your own, you could enable whatever authentication options you'd like; it's using the standard python social-auth authentication backend, and they have implementations available for just about every oauth backend you might be able to imagine.

Cheers, and good luck!

**Comment by johanbove** [comment]
Totally understand @coddingtonbear ; thanks for the speedy and clear response! Just wanted to add this here as a potential link between the IndieWeb and TaskWarrior, riding the decentralization hype.
