### ISSUE TITLE
Port blocked by work network

### ISSUE THREAD

**Issue by MartyLake** [coddingtonbear/inthe.am#315]
Hey, 
After changing work company, I was sad to realize the port used by inthe.am is blocked. I tried to convince the IT to open this port for me, without much success.

Is it possible to push the data over port `443` instead?

Probably linked with https://github.com/coddingtonbear/inthe.am/issues/271

**Comment by MartyLake** [comment]
poke @coddingtonbear ?

**Comment by coddingtonbear** [comment]
Sorry @MartyLake, the situation and workaround are unchanged from #271. Good luck!

**Comment by MartyLake** [comment]
@coddingtonbear  : IT are willing to open the port by associating it with static IP addresses. Can you share with me the known static IP addresses, if any ?

**Comment by coddingtonbear** [comment]
You can look up the current IP easily enough by just running `ping taskwarrior.inthe.am`; that being said, that'll only help for the time being.  At some point, I'm expecting to move Inthe.AM onto a cloud hosting provider, and at that point, there will not be a predictable IP any longer.

**Comment by MartyLake** [comment]
IT opened the port for me and it works now yay :D! Let's hope you can find a way to pin a static IP once you move to cloud hosting.

**Comment by coddingtonbear** [comment]
Sorry to break this to you, @MartyLake, but that is not a thing I'm going to even be thinking about. Hopefully you develop another workaround by that point!
