### ISSUE TITLE
How to configure the default taskwarrior report / context?

### ISSUE THREAD

**Issue by doronbehar** [coddingtonbear/inthe.am#316]
My `~/.taskrc` at my computer is pretty long - 227 lines. I define in it a lot of contexts, udas and reports' filters. To view my regularly attended classes, I have a "default" context I call `home` and I always view it with the report `ls`. I copied it (without the `taskd` settings to "Custom .taskrc" text box and hit save.

Still, In inthe.am's web interface, I can see many tasks I'm not interested in - tasks which I don't see with the report `ls` and the context `home`. I guess having `context=` written there influences the report? But I tried using `default.command=ls` so the tasks I'll see there will be of the report `ls` but I still saw the same old uninteresting tasks. Hence the question, is:

How do I configure the default report / context the interface shows me?

**Comment by coddingtonbear** [comment]
I'm afraid the interface doesn't support contexts right now, but if you'd like to contribute a patch that adds such support, definitely reach out in the gitter.im channel and we can discuss what that might look like.

Cheers!
