### ISSUE TITLE
inthe.am sync rejects sync with "recur:2 weeks"

### ISSUE THREAD

**Issue by d3zd3z** [coddingtonbear/inthe.am#318]
I have a recurring task with `recur:2 weeks` set. When I try to sync, I get the following error:

`Sync failed.  The Taskserver returned error: 500 The recurrence value '2 weeks' is not valid.`

Taskwarrior seems happy with "2 weeks".

I was able to make this work by using recur:2w instead, so this is not a high priority issue.

**Comment by Bckempa** [comment]
Found this when looking for a resolution to the same issue, tried removing the template issue and all instances before recreating with the "recur:2w" label instead, but got the same error.

**Comment by coddingtonbear** [comment]
I'm afraid my hands are tied as far as what the taskserver will accept; if you'd like to see about fixing that in the taskserver, you can feel free to file an issue on their board here: https://github.com/GothenburgBitFactory/taskserver.

Cheers!
