### ISSUE TITLE
After setting up bugwarrior, cannot sync. "The taskserver returned error: 504 Request too big"

### ISSUE THREAD

**Issue by d3zd3z** [coddingtonbear/inthe.am#319]
I'm not sure if I just have too many tasks. My .task directory is about 10MB. Is this just beyond what taskwarrior is intended to support.

Possible workarounds are to make another .task directory just for this one large github project.

**Comment by coddingtonbear** [comment]
I can't say how big folks' task lists are off-hand, but I'm struggling to imagine how you might be managing five "Anna Karenina"s worth of tasks!  Some back-of-the-napkin math makes me think you might have something around 20,000 tasks; is that accurate, and, if so, are you some kind of superman?

**Comment by d3zd3z** [comment]
It's actually only around 1500. It seems that bugwarrior is pulling in all of the github comments as annotations, which is making a lot of the tasks quite large. I'm still trying to figure out how to best manage this. There are lots of these issues that I can tell from the subject don't apply to me, but github's notification system isn't smart enough to do this for me.

It sounds like my best approach might be to put these in a separate .task directory, and then I should be able to sync my regular stuff.

**Comment by coddingtonbear** [comment]
So many changes have occurred over the last few months, I'm betting this is resolved now?  Cheers!
