### ISSUE TITLE
Tabular view (tw reports)

### ISSUE THREAD

**Issue by linuxcaffe** [coddingtonbear/inthe.am#32]
The current task listing is brilliant for mobile, and good on a desktop, but at a certain point (a lot of tasks and projects) overview, and the ability to see the full details for more than six tasks,becomes more important. 
An html rendering of task reports would be awesome, and most especially if those reports could be rendered from the users own configurations. If users could create custom reports in their .taskrc, and have those reports presented in lively javascripts, that would be an excellent alternative to the present low-density view.

I imagine a report-selector and filter-dialog at the top.

**Comment by coddingtonbear** [comment]
At the moment this isn't likely to ever make it onto the roadmap; if you'd like to add such a feature, though, I'd be glad to review/merge your work.  Let me know if you need any pointers on how to get a pull request put together, though!

Cheers,
Adam
