### ISSUE TITLE
Expired site certificate

### ISSUE THREAD

**Issue by ixil** [coddingtonbear/inthe.am#320]
The `inthe.am` certificate expired.
Expired on `1/20/2020, 12:02:54 AM (Central European Standard Time)`.

Syncing is working fine (for me), it's merely the website.

**Comment by coddingtonbear** [comment]
Thanks for the heads-up @ixil!  Although the automatic certificate renewal does appear to have been running, I still hadn't configured nginx to reload itself periodically so it might be able to access that cert after it has been renewed.  Fixed now!

Cheers!
