### ISSUE TITLE
Developer interested in learning more technical details and possibly contributing

### ISSUE THREAD

**Issue by NGenetzky** [coddingtonbear/inthe.am#325]
### Intro

I have been using your service for a while - so thank you @coddingtonbear , you deserve a :trophy: . I have found it very helpful, and I think that I might have even quit using TaskWarrior at some point if it wasn't for the service. So you could easily say that I am somewhat invested in the future of the service and the components on which it is built.

### What am I familiar with?

- python (low level + some REST services)
- docker
- packaging for Linux (I help maintain Disto built using Yocto)
- vagrant (with libvirt not virtualbox)

### Current Plan

I am considering getting a [local development environment setup based on the docs](https://intheam.readthedocs.io/en/latest/development/development_environment_setup.html). I intend to catch up on status and any investigation of Self-hosting #291 . 

### So what's the point of this issue anyway?

I am currently unable to visualize how the components in the repository fit together at a high level. Could you elaborate on the high-level technical system view of the service? Could you relate these components back to the repository?

**Comment by coddingtonbear** [comment]
I have no idea how i missed this message!  Yes -- definitely, absolutely; let's talk.  I just sent you an e-mail.

Cheers!
