### ISSUE TITLE
Expired Certificate makes inthe.am site UI unusable

### ISSUE THREAD

**Issue by ppmclala** [coddingtonbear/inthe.am#327]
![image](https://user-images.githubusercontent.com/35923/82270225-15bfbd00-9942-11ea-924a-827117ed716c.png)

Expired May 18, 2020 7:05 ET.  Ignoring the warnings and proceeding using Chrome or Brave results in errors in the app.

![image](https://user-images.githubusercontent.com/35923/82270509-0c832000-9943-11ea-80a6-3b8c40a1cc84.png)

Task sync still works fine.

**Comment by coddingtonbear** [comment]
Fixed!
