### ISSUE TITLE
Sync failed.  The Taskserver returned error: 500 Client sync key not found.

### ISSUE THREAD

**Issue by Trial-In-Error** [coddingtonbear/inthe.am#331]
This has happened before, and I believe it was a capacity (diskspace?) issue on the hosts? Anyways, it's happening again!

**Comment by coddingtonbear** [comment]
I'm afraid it's not disk space; there's plenty available right now.  Unfortunately it'll be at least a few days before I might be able to find a few minutes to look into this; so I recommend instead resetting your taskd data & re-syncing from scratch if you need sync to work anytime soon.

**Comment by Trial-In-Error** [comment]
Sorry - can you explain which process you mean? I'm a little unclear on the terminology.

1. Trash local task store and then sync from inthe.am
2. Trash inthe.am task store, then sync init from local
3. Trash client sync keys and use new sync keys for inthe.am
