### ISSUE TITLE
Forwarding emails from GMail

### ISSUE THREAD

**Issue by StephanMeijer** [coddingtonbear/inthe.am#333]
When configuring the option to _Create new tasks by sending an email message_, I wanted to forward automatically from GMail, so my clients can send me tasks.

Because there is a check on subject, I cannot receive the confirmation code I need to enter in GMail.

**Comment by coddingtonbear** [comment]
I'm not sure I follow -- what is this confirmation code you're mentioning?

**Comment by StephanMeijer** [comment]
@coddingtonbear https://tryshift.com/blog/gmail-hub/how-to-set-up-gmail-autoforward-to-from/

**Comment by coddingtonbear** [comment]
I'm not sure I understand the connection here -- you mean you're trying to autoforward via a gmail account instead of just e-mailing directly to your inthe.am e-mail address?  What benefit does that give you?

**Comment by StephanMeijer** [comment]
@coddingtonbear It allows me to automate some things without using the API. I could insert new tasks from a Google Form using email instead of making a HTTP API call to inthe.am.

**Comment by arozans** [comment]
I have a similar request. My use case: I receive some mails from a specific sender (e.g. "Your package awaits there and the e for next 5 days"). I would like to make a filter in GMail that forwards such messages to my inthe.am account so task is created. Sadly without an ability to confirm @inthe.am mail, it is not possible.

**Comment by StephanMeijer** [comment]
@arozans Message me for a temporary solution :)

**Comment by StephanMeijer** [comment]
@arozans Is there a way for recognizing what emails are `@gmail.com` and which ones are GSuite? Maybe we can write our own solution on this problem.

**Comment by coddingtonbear** [comment]
I've created a new enhancement (#375) that tracks a feature that might help with this.
