### ISSUE TITLE
inthe.am certificate has expired (Sep 16th 2020)

### ISSUE THREAD

**Issue by benallan** [coddingtonbear/inthe.am#335]
It looks like the certificate might have expired again:
![cert](https://user-images.githubusercontent.com/12690582/93412827-e792bf80-f8d8-11ea-9b87-4c25fdf5042f.png)

```
Not After   16/09/2020, 08:02:46 (Japan Standard Time)
```

Thanks.

**Comment by coddingtonbear** [comment]
Thanks for the heads-up @benallan -- I've reloaded nginx so it can see its new automatically-renewed certificate and the site is back again.  I swear I set up a cronjob for doing that periodically, but clearly there's something wrong there.

Cheers!

**Comment by coddingtonbear** [comment]
Found the problem!  I was running `/usr/bin/service nginx reload` instead of `/usr/sbin/service nginx reload`.

**Comment by benallan** [comment]
Thanks a lot! Glad you found the problem with the cronjob so hopefully you don't have to worry about this in future.
