### ISSUE TITLE
Docker host environment /var/log/daemon.log slowly fills host disk space

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/inthe.am#339]
This caused an outage for most of the day; clearly some logrotate settings need to be adjusted.

**Comment by coddingtonbear** [comment]
As it turns out; logrotate was already set up correctly!  It's just that it runs only 1x/day unless you specifically set it up to run more often.  I've done that now.

**Comment by renefritze** [comment]
Did you consider limiting the containers' logs too? I usually add something like this to docker's `daemon.json`
```
{
	"log-driver": "json-file",
	"log-opts": {"max-size": "10m", "max-file": "3"}
}
```

**Comment by coddingtonbear** [comment]
Didn't, but only kind of know what I'm doing!  I'm not sure how much time you have these days, but are you up for helping maintain things?

**Comment by renefritze** [comment]
Sorry, no. I cannot commit to any continuous help.

**Comment by DanielSchetritt** [comment]
@coddingtonbear , I think it's happening again. I would like to try to help you maintain this.

**Comment by coddingtonbear** [comment]
Fixed, @DanielSchetritt -- thanks for the heads-up !  Awesome; thanks for offering.   I'm planning on putting out an official call for maintainers soon (probably via a toast message when logging-in to the site). Click on that link when you see it.
