### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by arozans** [coddingtonbear/inthe.am#340]
Hey,

since today i'm having 
`Could not connect to inthe.am 53589
Sync failed.  Could not connect to the Taskserver.`

Filing gh issue as requested on gitter few weeks ago when similar case was detected 👍 
Thx

**Comment by coddingtonbear** [comment]
Thanks for the heads-up!  I'm actually not sure what went wrong -- it looks like it just stopped processing tasks around `2020-11-19 15:40:18`.  I've restarted it now (as the monitoring _should_ have done without me), and it appears to be running once again.

**Comment by arozans** [comment]
it works fine now. Thanks

**Comment by coddingtonbear** [comment]
It _looks_ like it's continually crashing, actually; there's a misbehaving client connecting to the taskserver without closing its connection.  I'm going to see what I can do to block that IP.
