### ISSUE TITLE
DRF Trello synchronisation issue 

### ISSUE THREAD

**Issue by leikoilja** [coddingtonbear/inthe.am#348]
Previously mentioned in https://github.com/coddingtonbear/inthe.am/issues/330:

The issue is with Trello synchronisation. None of the tasks seem to be syncing.
When I press "Force resync" from the configuration I get Django rest error saying GET requests are not allowed
![image](https://user-images.githubusercontent.com/10655107/104018062-81001d00-51b9-11eb-8b85-3f1cce6382d6.png)

**Comment by coddingtonbear** [comment]
OK!  All sorted out now, @leikoilja -- if you click on either of those buttons (and it sounds like you do want to click on "Force Resynchronization") they should totally work now.

Cheers & good luck!
