### ISSUE TITLE
Feature Request: Show completed tasks in web UI?

### ISSUE THREAD

**Issue by schmitmd** [coddingtonbear/inthe.am#350]
I'm not sure if this is something that everyone would want, but I think it'd be really neat to see my completed tasks in the web UI instead of getting redirected to the Getting Started page by default.  Not urgent.

**Comment by coddingtonbear** [comment]
Unfortunately, not likely to happen given that it is a pretty niche need and would require some API changes.  If you want to consider working on a PR supporting this, though, definitely feel free to reach out on the gitter channel, and I can walk you through what the constraints around such a feature would be and how you might work around them in putting together a PR, though!
