### ISSUE TITLE
inthe.am syncrhonization stopped working

### ISSUE THREAD

**Issue by gbstan** [coddingtonbear/inthe.am#356]
It seems that synchronisation with inthe.am stopped working suddenly.

I get the following message each time I try to synchronise with "task sync": Sync failed.  Either your credentials are incorrect, or your account doesn't exist on the Taskserver. Everything was working perfectly for months until recently.

I have reset the whole system (https://inthe.am/configure/danger-zone -> Delete your account information -> Clear Task Data) and still get the same error message after reconfiguring everything and executing "task sync init".

Not sure what do do next.

**Comment by owenpearson** [comment]
i'm getting this too, I guess there's a problem with the server?

**Comment by qchristianp** [comment]
yes, I can not create an account it says server error 500

**Comment by 0x6d64** [comment]
Works again for me :partying_face:

**Comment by coddingtonbear** [comment]
The taskd server was briefly not able to access its task data due to a little bug in a tool Inthe.AM uses for mounting the encrypted volume holding task data: https://github.com/containers/docker-lvm-plugin/issues/59.  I've just a moment ago walked through the steps for cleaning things up, and the server is again up.

**Comment by nickwynja** [comment]
`task sync` is timing out now.

```
$ task sync
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
```

**Comment by miguelpduarte** [comment]
I also was unable to sync some hours ago but can confirm it is now working again.

**Comment by miguelpduarte** [comment]
It seems to have stopped working once again. The issue now seems to be being unable to connect to the taskserver. From the log in the website:
```
Handshake failed. Error in the pull function. Sync failed. Could not connect to the Taskserver..
```
