### ISSUE TITLE
Error when try to delete my account

### ISSUE THREAD

**Issue by szaffarano** [coddingtonbear/inthe.am#358]
When I try to delete my `inthe.am` account, i.e. going to `Configuration` -> `Danger Zone` -> `Delete My Account` I get an HTTP 500 error code.

## Response Header

```
HTTP/1.1 500 Internal Server Error
Server: nginx/1.19.2
Date: Sat, 08 May 2021 18:41:01 GMT
Content-Type: text/html
Content-Length: 27
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Vary: Origin, Cookie
```

## Response Body

```
<h1>Server Error (500)</h1>
```

**Comment by cam-barts** [comment]
I am also running into this issue. I dropped a chat in the gitter. Would love some feedback from @coddingtonbear

**Comment by coddingtonbear** [comment]
There's definitely a bug that prevents account deletion in certain cases -- I at the moment think it's probably related to trying to delete your account more than once, but I haven't dug into it in any significant depth, and I really don't have a ton of time on my hands.  In any case, I'd <3 a PR fixing it -- there's even a docker environment you can bring up easily that will help you reproduce the issue & create a patch.

**Comment by szaffarano** [comment]
Hi @coddingtonbear 
I've found the error, in `taskd_services/http/api.py`, method `delete`, it's necessary to pass the user key instead of the user id to `taskd`:
```diff
-        command = [TASKD_BINARY, "remove", "user", self.org_name, self.user_name]
+        command = [TASKD_BINARY, "remove", "user", self.org_name, self.user_key]
```
But even though this change makes the method works, the user is only removed from taskd and not from the inthe_am DB, Indeed I can log in again, but I got an `HTTP 500` error.

I'll try to submit a PR, but I have some questions:

1. I had to create the `inthe_am` org by hand:
   ```
      $ docker-compose exec taskd sh
      $ taskd org add inthe_am
   ```
   Is it ok? I wonder if the org should be created as part of the environment initialization, or if I missed some steps.
2. I had to update `flask-sqlalchemy` because of a bug related to the DB initialization.  Are you aware of that? I mean, I don't get how the environment works without this upgrade.
   ```diff
-flask-sqlalchemy==2.4.2
+flask-sqlalchemy==2.5
   ```

Thanks

**Comment by szaffarano** [comment]
Ok, I figured out why the org wasn't created! I had t remove the `generated` flag file from `$TASKDDATA/pki/generated`

**Comment by cam-barts** [comment]
I was just sitting down to take a look at this and you beat me to it, Thanks @szaffarano! Let me know if there is anything I can do to help!

**Comment by szaffarano** [comment]
Hi guys,
I've just created a PR.  I wanted to do at least one unit test, but I prefer submitting it so you can review it.  I added some minor changes as well, mainly related to configuration stuff, because I had some problems fully configuring the local environment.

**Comment by coddingtonbear** [comment]
All released, thanks to @szaffarano's contributions!  I think you should be able to delete/recreate accounts now without any trouble.

Cheers!
