### ISSUE TITLE
Email-to-task fails if subject "New" is capitalized

### ISSUE THREAD

**Issue by vEnhance** [coddingtonbear/inthe.am#364]
Today I am trying the email-to-add feature and was surprised to find that it worked fine for the subject "new" or empty subject but not "New" with the capital N. I tested this using a web gmail client and native ipad mail.

Oddly, the other undocumented pass-listed subjects "Add", "add", "Create", "create" all seemed to work fine for me.

Obviously not a high priority since it's trivial to workaround. Feel free to close if you can't reproduce.

**Comment by coddingtonbear** [comment]
I'm afraid I don't see how that might be happening given that the logic for that lives here: https://github.com/coddingtonbear/inthe.am/blob/bbd75934a5ffc1a9608dfa5daf77c089bdf16311/inthe_am/taskmanager/tasks.py#L146 -- if you're still encountering this issue, though, reach out and maybe I can do a little troubleshooting with you.
