### ISSUE TITLE
Web interface displays blank page after login

### ISSUE THREAD

**Issue by morganmay** [coddingtonbear/inthe.am#372]
After logging in with my Google account, inthe.am's web interface doesn't load properly; all I see is a blank page. This happens regardless of which browser, device, or Google account I use. Task syncing with my local taskwarrior instance seems to still be working; `task sync` generates no errors.

I've attached [the HTML source](https://github.com/coddingtonbear/inthe.am/files/7191060/view-source_https___inthe.am.html.txt).

**Comment by coddingtonbear** [comment]
You _might_ have been trying to log-in while the server was particularly busy or there was a temporary problem with either Inthe.AM, our hosting provider, maybe the certificate, or even possibly our integration with google's auth service; unfortunately, though, I don't have any logs going back anywhere near that far, so I can't really tell!   I'm at the moment able to log-in successfully, so I'm going to assume you'd be able to log-in now.  If you _did_ try to log-in again and had trouble, just respond here and I can dig into the logs to see what might be happening.
