### ISSUE TITLE
Tasks Not Displaying

### ISSUE THREAD

**Issue by djotaku** [coddingtonbear/inthe.am#388]
Different issue/symptoms than #352 

I don't remember which I noticed first, that I would get the error:

Sync failed.  The Taskserver returned error: 500 Client sync key not found.

when using task sync or having a blank white screen on inthe.am.

By going to the Danger Zone and clearing task data, I can now run task sync on the commandline without error.

If I try to create a task on inthe.am - I can fill out the fields, but nothing appears on the screen or is synced back to the commandline. 

I did not do: 

"you will need to at least clear any synchronizing clients' backlog.data for them to be able to synchronize again."

since I didn't get any errors when running task sync.

In my logs, here are the last few errors:

`

2022-02-14T22:25:52.375138Z | An error was encountered when attempting to sync Inthe.AM's UI with the Taskserver: No data.location specified!.
-- | --
2022-02-14T22:25:51.674279Z | Synchronization  with other taskd servers is no longer supported.  Your account has been  automatically reconfigured to synchronize with Inthe.AM's built-in task  server.You may need to re-configure your local taskwarrior instances.

`
Those both come after the last time the UI worked for me

**Comment by coddingtonbear** [comment]
I *think* I've fixed-up your account for you now.  Tbh, I'm not exactly sure I understand what happened, but at some point the server became convinced that your account was using a long, long obsolete feature that allowed inthe.am to synchronize with 3rd-party taskd servers.  I've reverted your task list to right before it came to that mistaken conclusion, and think you should be alright now!

Locally, you'll probably want to clear your task list and re-synchronize with inthe.am, but vice-versa would probably be fine, too.

Good luck!

**Comment by djotaku** [comment]
It wouldn't sync. Now it just shows a white page for me - not even the top menu

**Comment by djotaku** [comment]
Just deleted my account to start again

**Comment by coddingtonbear** [comment]
Just to be clear -- I _expect_ that it wouldn't sync.  You would have to start from a clean task list for it to work given that your local copy of your task list and that of inthe.am's UI will at that point have a different history -- that's why I said you would need to "clear your task list and re-synchronize with inthe.am".
