### ISSUE TITLE
The recurrence value 'P1M' is not valid.

### ISSUE THREAD

**Issue by sclee15** [coddingtonbear/inthe.am#394]
When I sync with in the am server,
I get this error.

The recurrence value 'P1M' is not valid.

**Comment by coddingtonbear** [comment]
I'm afraid you're using a too-new version of recurrence.  The recurrence type you've used is, I believe, valid for only Taskserver 1.2 and above.  Taskserver 1.1 is used here, though.  If you convert to the earlier recurrence format, you should be ok.

Good luck!
