### ISSUE TITLE
Unable to regenerate expired certificate

### ISSUE THREAD

**Issue by CarlosMFdz** [coddingtonbear/inthe.am#396]
It appears my certificate has expired and i cant figure out how to update it.
I even tried using the API endpoint to no avail. 
`curl -X POST -H "Authorization: Token MYAPIKEY" -i https://inthe.am/api/v2/user/generate-new-certificate/`
`HTTP/1.1 200 OK
Server: nginx/1.19.2
Date: Thu, 23 Jun 2022 00:44:35 GMT
Content-Length: 0
Connection: keep-alive
Vary: Accept, Origin
Allow: POST, OPTIONS
X-Frame-Options: SAMEORIGIN`

The response indicates the request was successful, but still, when I go to re-download the cert it is still the same old one.

**Comment by coddingtonbear** [comment]
The certificates are automatically re-generated a little while before their expiry date.  You should be able to download a new certificate by going to the site as you approach your certificate's expiry.  Good luck!
