### ISSUE TITLE
Clear Task Data not working as expected

### ISSUE THREAD

**Issue by linnabraham** [coddingtonbear/inthe.am#397]
All of the tasks data reappear in a short while after the `Clear Task Data` button is pressed. 
`task sync` says successful. No changes

**Comment by coddingtonbear** [comment]
I'm _assuming_ you're re-synchronizing after pressing the "Clear Task Data" button or you have another client somewhere resynchronizing via a cron task.  The code for the clear task data button is here: 

https://github.com/coddingtonbear/inthe.am/blob/development/inthe_am/taskmanager/viewsets/user.py#L386

which calls:

https://github.com/coddingtonbear/inthe.am/blob/4b12cc09187a2af526c38a36a03b6dedfe74d8ed/inthe_am/taskmanager/models/taskstore.py#L861

If you can demonstrate a bug there, though, please file a pull request fixing it!
