### ISSUE TITLE
Google Authentification results in Server Error (500)

### ISSUE THREAD

**Issue by felixschurk** [coddingtonbear/inthe.am#426]
Hei, 
I noticed that since yesterday when I try to login with my google account that the server results in Server Error (500). 
This also occurs when I use another Google Account.

Was there maybe a change in the Google API?

Best Felix

**Comment by sadger** [comment]
Same for me!

**Comment by coddingtonbear** [comment]
There was some emergency server maintenance at Inthe.AM's web provider, Linode, and unfortunately Inthe.AM doesn't recover gracefully from abrupt outages like that.

I've manually fixed the volume mounting problem, though, now, and things are back up!

**Comment by felixschurk** [comment]
Thank you a lot for the quick fix and in general for the service!
