### ISSUE TITLE
edit annotations

### ISSUE THREAD

**Issue by linuxcaffe** [coddingtonbear/inthe.am#48]
At the moment, one can add an annotation, or delete an annotation, but I don't see a way to edit an existing annotation. Perhaps a logical thing would be an "edit" icon near (or opposite) the little "x" used to delete annotations, or maybe clicking anywhere on the annotation (except the little "x") would open it up in a text edit thingy ?

**Comment by coddingtonbear** [comment]
At the moment this isn't likely to ever make it onto the roadmap; if you'd like to add such a feature, though, I'd be glad to review/merge your work.  Let me know if you need any pointers on how to get a pull request put together, though!

Cheers,
Adam
